version: '2'
services:
  cluster:
    start_on_create: true
  elasticsearch3:
    scale: 1
    start_on_create: true
  elasticsearch1:
    scale: 1
    start_on_create: true
  elasticsearch-data1:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: cluster
        source_port: 9200
        target_port: 9200
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  elasticsearch2:
    scale: 1
    start_on_create: true
  elasticsearch-data3:
    scale: 1
    start_on_create: true
  elasticsearch-sysctl1:
    scale: 1
    start_on_create: true
  elasticsearch-data2:
    scale: 1
    start_on_create: true
  elasticsearch-sysctl3:
    scale: 1
    start_on_create: true
  elasticsearch-sysctl2:
    scale: 1
    start_on_create: true
