#docker
filebeat.config:
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']

setup.kibana:
  host: "kibana:5601"




#rpm
filebeat.prospectors:

- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/firewalld
    - /var/log/messages
    - /var/log/secure

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

tags: ["service-X", "web-tier"]

fields:
  env: dev
  project: tlo
  role: api

fields_under_root: true

setup.kibana:
  host: "http://192.168.200.112:80"

output.logstash:
  hosts: ["127.0.0.1:5044"]

#logging.level: debug
