version: '2'
services:
  logstash:
    image: rancher/dns-service
    external_links:
    - logstash/logstash:logstash
  logspout:
    image: bekt/logspout-logstash:latest
    environment:
      ROUTE_URIS: logstash+tcp://logstash:5041
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
